apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  root-password: cGFzc3dvcmQ=    # "password" encodé en base64
  user-password: cGl6emE=        # "pizza" encodé en base64
