{{- if .Values.istio.enabled }}
{{- if .Values.istio.destinationRules.enabled }}

{{- if .Values.service.backend.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}-pizza-service
spec:
  host: {{ .Release.Name }}-pizza-service
  trafficPolicy:
    loadBalancer:
      simple: {{ .Values.istio.destinationRules.loadBalancer | default "ROUND_ROBIN" }}
    {{- if .Values.istio.destinationRules.connectionPool }}
    connectionPool:
      {{ toYaml .Values.istio.destinationRules.connectionPool | nindent 6 }}
    {{- end }}
{{- end }}

{{- if .Values.service.notification.enabled }}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}-notification-service
spec:
  host: {{ .Release.Name }}-notification-service
  trafficPolicy:
    loadBalancer:
      simple: {{ .Values.istio.destinationRules.loadBalancer | default "ROUND_ROBIN" }}
    {{- if .Values.istio.destinationRules.connectionPool }}
    connectionPool:
      {{ toYaml .Values.istio.destinationRules.connectionPool | nindent 6 }}
    {{- end }}
{{- end }}

{{- if .Values.service.frontend.enabled }}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}-pizza-frontend
spec:
  host: {{ .Release.Name }}-pizza-frontend
  trafficPolicy:
    loadBalancer:
      simple: {{ .Values.istio.destinationRules.loadBalancer | default "ROUND_ROBIN" }}
    {{- if .Values.istio.destinationRules.connectionPool }}
    connectionPool:
      {{ toYaml .Values.istio.destinationRules.connectionPool | nindent 6 }}
    {{- end }}
{{- end }}

{{- end }}
{{- end }}