{{- if $.Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ $.Release.Name }}-pizza-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    {{- range $.Values.istio.gateway.hosts }}
    - {{ . }}
    {{- end }}
    tls:
      httpsRedirect: false
  {{- if $.Values.istio.gateway.tls.enabled }}
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    {{- range $.Values.istio.gateway.hosts }}
    - {{ . | quote }}
    {{- end }}
    tls:
      mode: SIMPLE
      credentialName: {{ $.Values.istio.gateway.tls.secretName | quote }}
  {{- end }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $.Release.Name }}-virtualservice
spec:
  hosts:
  {{- range $.Values.istio.gateway.hosts }}
  - {{ . }}
  {{- end }}
  gateways:
  - {{ $.Release.Name }}-pizza-gateway
  http:
  # CORS preflight
  - match:
    - method:
        exact: OPTIONS
      uri:
        prefix: /api
    corsPolicy:
      allowOrigins:
      {{- if eq (index $.Values.istio.virtualService.corsPolicy.allowOrigins 0) "*" }}
      - exact: "*"
      {{- else }}
        {{- range $.Values.istio.virtualService.corsPolicy.allowOrigins }}
        - exact: {{ . }}
        {{- end }}
      {{- end }}
      allowMethods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
      allowHeaders:
        {{- range $.Values.istio.virtualService.corsPolicy.allowHeaders }}
        - {{ .  }}
        {{- end }}
      exposeHeaders:
        {{- if kindIs "slice" $.Values.istio.virtualService.corsPolicy.exposeHeaders }}
          {{- range $.Values.istio.virtualService.corsPolicy.exposeHeaders }}
          - {{ . }}
          {{- end }}
        {{- else }}
        - {{ $.Values.istio.virtualService.corsPolicy.exposeHeaders }}
        {{- end }}
      {{- if $.Values.istio.virtualService.corsPolicy.allowCredentials }}
      allowCredentials: {{ $.Values.istio.virtualService.corsPolicy.allowCredentials }}
      {{- end }}
      {{- if $.Values.istio.virtualService.corsPolicy.maxAge }}
      maxAge: {{ $.Values.istio.virtualService.corsPolicy.maxAge }}
      {{- end }}
    route:
    - destination:
        host: {{ $.Release.Name }}-pizza-service.default.svc.cluster.local
        port:
          number: {{ $.Values.service.backend.port }}

  # Backend routes
  {{- if $.Values.istio.virtualService.routes.backend.paths }}
  {{- range $.Values.istio.virtualService.routes.backend.paths }}
  - match:
    - uri:
        prefix: {{ . }}
    route:
    - destination:
        host: {{ $.Release.Name }}-pizza-service.default.svc.cluster.local
        port:
          number: {{ $.Values.service.backend.port }}
  {{- end }}
  {{- end }}

  # Notification routes
  {{- if $.Values.istio.virtualService.routes.notification.paths }}
  {{- range $.Values.istio.virtualService.routes.notification.paths }}
  - match:
    - uri:
        prefix: {{ . }}
    route:
    - destination:
        host: {{ $.Release.Name }}-notification-service.default.svc.cluster.local
        port:
          number: {{ $.Values.service.notification.port }}
  {{- end }}
  {{- end }}

  # Frontend default route
  {{- if $.Values.istio.virtualService.routes.frontend.isDefault }}
  - route:
    - destination:
        host: {{ $.Release.Name }}-pizza-frontend.default.svc.cluster.local
        port:
          number: {{ $.Values.service.frontend.port }}
  {{- end }}
{{- end }}