apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-notification-service
spec:
  replicas: {{ .Values.replicaCount.notification }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-notification-service
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-notification-service
    spec:
      containers:
      - name: notification-service
        image: {{ .Values.image.registry }}/{{ .Values.image.repository.notification }}:{{ .Values.image.tag.notification }}
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-notification-service
spec:
  selector:
    app: {{ .Release.Name }}-notification-service
  ports:
  - port: {{ .Values.service.notification.port }}
    targetPort: {{ .Values.service.notification.targetPort }}
  type: {{ .Values.service.type }}